Add item requests
OlegSharomov/java-shareit pull request #3
Opened 2022-09-11 11:14 UTC by OlegSharomov

2022-09-15 13:47 UTC, SnikerZi requested changes
Привет, ты написал неплохой код, однако нужно исправить тесты . Общая структура кода верна, остались мелкие недочеты

2022-09-15 13:47 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>              throw new ValidationException("Статус бронирования уже подтвержден");
на 79 строке рекомендую использовать примитивное логическое выражение для улучшения читаемости кода.
if (Boolean.TRUE.equals(b)) {
  foo();
}

2022-09-15 13:47 UTC, SnikerZi commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        Assertions.assertEquals(re.getMessage(), "Данные бронирования можно изменять только через метод PATCH");
у тебя неправильный порядок аргументов, сначала должен идти ожидаемый результат, потом вводимый.
Аналогично на строках 87, 97, 109

2022-09-15 13:47 UTC, SnikerZi commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        when(bookingRepository.findAllByBookerIdAndStatusOrderByStartDesc(eq(1L), eq(WAITING)))
Тут можно убрать использование eq() и передавать параметры напрямую.
Аналогично на строках 344, 596, 620.

2022-09-15 13:47 UTC, SnikerZi commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +        assertEquals(re.getMessage(), "Вещь с переданным id = 1 отсутствует в хранилище");
Неправильный порядок аргументов.
Аналогично на строках 216, 225, 285, 350, 360, 372, 387, 428, 436, 445, 455, 465, 567, 577

2022-09-15 13:47 UTC, SnikerZi commented on src/test/java/ru/practicum/shareit/user/service/UserServiceTest.java
> +        assertEquals(usersDto, Collections.emptyList());
Неправильный порядок аргументов.
Аналогично на строках 139, 147, 155, 164

2022-09-15 19:16 UTC, OlegSharomov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        when(bookingRepository.findAllByBookerIdAndStatusOrderByStartDesc(eq(1L), eq(WAITING)))
Я изначально пытался так сделать, но получал такую ошибку:
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
2 matchers expected, 1 recorded:
-> at ru.practicum.shareit.booking.service.BookingServiceTest.shouldReturnListDtoWhenFromAndSizeIsNullAndStateIsWaiting(BookingServiceTest.java:326)

This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(any(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(any(), eq("String by matcher"));

For more info see javadoc for Matchers class.

2022-09-16 20:24 UTC, SnikerZi commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceTest.java
> +        when(bookingRepository.findAllByBookerIdAndStatusOrderByStartDesc(eq(1L), eq(WAITING)))
Тут тебе написали, что можно использовать eq с проверочной строкой, то есть первым аргументом ты передаешь твою функцию , вторым проверочное значение.

2022-09-16 20:25 UTC, SnikerZi approved these changes
Ты написал отличную программу. Спасибо за правки, ты молодец.

2022-09-20 09:15 UTC, merged